name : Build and Deploy

on : [push,pull_request]

# on: 
#   push:
#     branches: ["manin_branch","feature branch"] 

# on: 
#   push:
#     branches:
#        -"main_branch"
#        -"feature_branch"
#   pull:
#      branches:
#        -"test_branches"   

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
       - name: pulling git repo
         uses: actions/checkout@v2
       - name: Install python version 3.10.5
         uses: actions/setup-python@v2  
         with: 
            python-version: "3.10.5"
       -name: update pip
        run: python -m pip install --updgrade pip
       -name: install all dependencies
        run: pip install -r requirements.txt       